#!/bin/bash
for (( i=1; ; ++i)); do
	printf "\033[7;34m===============Testcase \033[7;35m%2d\033[7;34m===============\033[0m\n" $i
	printf "Generating Testdata ... "
	/usr/bin/time -f "%Us" ./
	printf "Running bill125's Program ... "
	/usr/bin/time -f "%Us" ./
	printf "Running AC/Brute Program ... "
	/usr/bin/time -f "%Us" ./
	printf "Checking ... "
	diff test.out test2.out > /dev/null
	if [[ $? -eq 0 ]]; then
	printf "[\033[7;32mCorrect!\033[0m]\n"
	else
	printf "[\033[7;31mDifferent!\033[0m]\n"
	break
	fi
	sleep 1
done
